Created an adapter for South Africa
openaq/openaq-fetch pull request #722
Opened 2020-05-01 12:03 UTC by magsyg

Created an adapter for South Africa, with data from http://saaqis.environment.gov.za/Report/HourlyReports.

This source has PM2.5, PM10, So2, No2 and O3 values, and around 400 sensors, which should be updated hourly

Is a part of issue #542

2020-05-22 11:29 UTC, magsyg commented on adapters/southafrica.js
> +  var getPollutant = function (pollutant) {
The source has a lot of different parameters such as NOX, Amb Temp, WS, rain and such, and the getPollutant method should help with filtering out those values we do not want in the database, should I still replace it?

2020-05-22 21:31 UTC, sruti commented on adapters/southafrica.js
> +  var getPollutant = function (pollutant) {
Ah for that you can use [removeUnwantedParameters](https://github.com/openaq/openaq-fetch/blob/develop/lib/utils.js#L99)

2021-04-23 23:02 UTC, sruti requested changes
So close! A few minor things and it will be good to go.

2021-04-23 23:02 UTC, sruti commented on adapters/southafrica.js
> +        m.date = parseDate(v.DateVal);
Looks like sometimes `dateVal` comes back `null`. For example: 
```
{"IP":null,"display":true,"STA_O3Factor":1.0,"STA_O3BFactor":0.0,"serialCode":304,"name":"Driftsands","location":"Driftsands Nature Reserve, Delft, Cape Town","city":"City of Cape Town","StGroup":null,"StGroupName":"Western Cape ","height":"37","latitude":"-33.991842","longitude":"18.653067","IndexColor":null,"IndexIcon":null,"IndexName":null,"environment":"N/A","GIS_Monitors":null,"GIS_channel":null,"GIS_Units":null,"GIS_LastRecivedValues":null,"timebase":60,"owner":"Western Cape Province","IndexValue":null,"Active":1,"UseMapView":1,"FileName":null,"ImageDescription":null,"ImageStatus":null,"NonContinuous":false,"AQSCODE":null,"STA_ImageData":null,"STA_Notes":"N/A","DateVal":null,"IndexValueDateTime":null,"STA_Target":"Urban","CBO_ItemIndex":2,"TargetId":18,"asix":null,"dateDisplay":"05/04/2021 10:00","monitors":[{"channel":2,"type":46,"value":"12.1","Lastvalue":"12.1","state":1,"name":"NO2","unit":"ppb","stationSerialCode":304,"stationName":"Driftsands","owner":"Western Cape Province","Color":null,"IndexIcon":null,"indexVal":0,"TimeBase":0,"StationTimeBase":60,"DateVal":null,"NumericFormat":5.3,"Pollutantname":"NO2","Description":"","asix":null,"isPolPos":false,"PollutantTimeBase":0,"PollutantID":1,"PctValid":75,"Active":1,"UseMapView":1,"isIndex":true,"indexName":null,"StationTag":"","ShortName":"Driftsands","County":"Western Cape"
```
On the website, it just reports it as `NO_REPORT_DATA` for the whole station so I would filter out any measurements that have null Date values

2021-04-29 15:57 UTC, sruti commented on adapters/southafrica.js
> +      location: s.location,
I actually meant for it to be `location: s.name` for all. I'll fix it

2021-04-29 15:58 UTC, sruti commented on adapters/southafrica.js
> +      if (v.value !== null) {
I might not have been clear in my explanation but wanted it to be ` if (v.value !== null && v.value !== '') {`

2021-04-29 15:59 UTC, merged