Rio adapater
openaq/openaq-fetch pull request #764
Opened 2020-07-21 01:44 UTC by zamandalee

A Rio de Janeiro adapter and source file.

- Trello ticket: https://trello.com/c/8fKDDjYw/35-add-rio-adapter
- Github issue: https://github.com/openaq/openaq-fetch/issues/500
- Data endpoint: http://www.data.rio/datasets/dados-hor%C3%A1rios-do-monitoramento-da-qualidade-do-ar-monitorar/geoservice?orderBy=Esta%C3%A7%C3%A3o
- Example data: https://services1.arcgis.com/OlP4dGNtIcnD3RYf/arcgis/rest/services/Qualidade_do_ar_dados_horarios_2011_2018/FeatureServer/2/query?where=Data%20%3E%20CURRENT_TIMESTAMP%20-%20INTERVAL%20%2731%27%20DAY&outFields=Data,CodNum,Esta%C3%A7%C3%A3o,SO2,NO2,CO,NO,O3,PM10,PM2_5,Lat,Lon&returnGeometry=false&outSR=4326&f=json

2020-10-08 00:53 UTC, sruti requested changes
Hi @zamandalee! Sorry for the long delay in looking at this. A couple of tiny fixes otherwise looks good to go. Thanks so much!

2020-10-08 00:53 UTC, sruti commented on adapters/rio.js
> +    attribution: [{ name: 'Data.rio', url: 'http://www.data.rio/' }],
Could you update the attribution name to `Prefeitura da Cidade do Rio de Janeiro – MonitorAr` and url to `http://www.rio.rj.gov.br/web/smac/exibeconteudo?id=4448505` please?

2020-10-08 00:53 UTC, sruti commented on sources/br.json
> +        "description": "Data.rio",
Could you update the description to 'Prefeitura da Cidade do Rio de Janeiro – MonitorAr'

2020-10-08 00:53 UTC, sruti commented on adapters/rio.js
> +    sourceName: 'Prefeitura da Cidade do Rio de Janeiro – MonitorAr',
Could you change the source name to 'Rio de Janeiro'?

2022-11-15 15:45 UTC, majesticio commented
I'm closing this PR because the source URL appears to be offline. We really appreciate your contribution and you're always welcome to reopen the PR if new info come to light. Thanks!

2022-11-15 16:57 UTC, majesticio commented
Pardon me! We reopened this because we see the source has been updated with an SSL to https://www.data.rio/datasets/dados-hor%C3%A1rios-do-monitoramento-da-qualidade-do-ar-monitorar/api

2023-07-12 14:05 UTC, russbiggs commented
@majesticio now that we have Rio city hall data do we close this?

2023-07-12 15:19 UTC, closed without merging