[DO NOT MERGE] Upload tool adapter
openaq/openaq-fetch pull request #768
Opened 2020-10-09 21:06 UTC by dqgorelick

2020-10-09 21:08 UTC, dqgorelick commented on adapters/upload_tool.js
> +    sourceName: a.sourceName,
Change this to be sourceName: source.name (add this argument)

2020-10-13 19:14 UTC, dqgorelick commented on adapters/upload_tool.js
> +              Bucket: 'upload-tool-bucket-dev',
Note: this currently expects the final S3 bucket for the files to exist in `upload-tool-bucket-dev`. This bucket needs to be changed to match what is in the [Upload tool](https://github.com/openaq/openaq-upload/pull/24) repo for production stage.

2020-10-13 19:16 UTC, dqgorelick commented on adapters/upload_tool.js
> +const UPLOAD_TOOL_BUCKET = 'upload-tool-bucket-dev'
Note: this currently expects the final S3 bucket for the files to exist in upload-tool-bucket-dev. This bucket needs to be changed to match what is in the [Upload tool](https://github.com/openaq/openaq-upload/pull/24) repo for production stage.

2020-10-15 04:47 UTC, sruti requested changes
hi

2020-10-20 17:59 UTC, dqgorelick commented on adapters/upload_tool.js
> +          results = results.concat(result);
nice catch!

2020-10-27 14:51 UTC, MichalCz commented
Hi,

I added this PR to make use of streaming and it actually does solve the issues that cause the errors.

2020-10-27 22:47 UTC, dqgorelick commented
Hi @MichalCz thank you for taking a look. It's really interesting seeing how you use the generator function! 

Merging :shipit:

2023-02-09 00:53 UTC, closed without merging