Bug/south australia
openaq/openaq-fetch pull request #957
Opened 2023-02-28 21:47 UTC by majesticio

Ready for review/PR. Wiki available at https://github.com/openaq/openaq-fetch/wiki/South-Australia-Environmental-Protection-Authority-(EPA)

2023-02-28 21:52 UTC, majesticio commented
closes #918

2023-03-23 22:01 UTC, russbiggs requested changes

2023-03-23 22:01 UTC, russbiggs commented on src/adapters/southaustralia.js
> +                    value: 1
This doesnt line up for CO, since its an 8 hour averaging period

2023-03-24 16:28 UTC, russbiggs commented on src/adapters/southaustralia.js
> +                    value: 1
each parameter is stored separately so it is possible. You'll likely need to make `value` a dynamic value based on some sort of `if..else...` logic and toggle between 8 and 1.

2023-03-28 19:56 UTC, merged