updated according to rubric
openaq/openaq-fetch pull request #986
Opened 2023-04-11 17:08 UTC by majesticio

adapter now uses parseFloat, let, luxon and got

2023-04-11 21:32 UTC, russbiggs requested changes

2023-04-11 21:32 UTC, russbiggs commented on src/adapters/au_act.js
> +      let data = formatData(JSON.parse(body), source);
this can be `const` its never changed

2023-04-11 21:32 UTC, russbiggs commented on src/adapters/au_act.js
> +  let units = {
this should be `const` its never reassigned

2023-04-11 21:32 UTC, russbiggs commented on src/adapters/au_act.js
> +  let parseDate = function (string) {
this should be `const` its never reassigned

2023-05-22 14:45 UTC, majesticio commented
merged into update-libraries

2023-05-22 14:45 UTC, closed without merging