removed old adapter au_sa.js
openaq/openaq-fetch pull request #987
Opened 2023-04-11 17:36 UTC by majesticio

adapter has been replaced by southaustralia.js.

2023-04-11 17:36 UTC, majesticio commented
Do we need to add this to the change log?

2023-04-11 21:28 UTC, russbiggs commented on src/adapters/CHANGELOG.md
> +and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
We're not going to follow semantic versioning so remove this

2023-04-11 21:28 UTC, russbiggs commented on src/adapters/CHANGELOG.md
> +## [0.0.1] - 04/11/2023
Just used the date since we arent following a versioning scheme

2023-04-11 21:28 UTC, russbiggs commented on src/adapters/CHANGELOG.md
> +All notable changes to this project will be documented in this file.
This changelog will only be relevant for adapters, so maybe language like "Changes to adapters wil lbe documented in this file"

2023-04-11 21:58 UTC, russbiggs requested changes

2023-04-11 21:58 UTC, russbiggs commented on src/adapters/CHANGELOG.md
> +Changes to adapters wil lbe documented in this file
typo at "wil lbe"

2024-02-05 02:10 UTC, russbiggs commented
@majesticio whats the status on this PR?

2024-02-05 15:20 UTC, majesticio commented
I'm closing this PR as theses changes have already been implemented.

2024-02-05 15:20 UTC, closed without merging